#!bin/bash

# Renames /Library/Desktop Pictures/High Sierra.jpg to oldHigh Sierra.jpg
# Renames /Library/Desktop Pictures/Sierra 2.jpg to High Sierra.jpg
# This should, in theory, upon reboot, make Sierra 2 the default desktop background.
# This will probably break in the next Major (10.14 etc) release of the OS. YMMV
# SCOUT IT ryne@wearescout.com 

mv /Library/Desktop\ Pictures/High\ Sierra.jpg /Library/Desktop\ Pictures/High\ Sierraold.jpg
mv /Library/Desktop\ Pictures/El\ Capitan\ 2.jpg /Library/Desktop\ Pictures/High\ Sierra.jpg
